services:
  backup-postgres-s3:
    image: 4labdev/postgres-bk-s3
    restart: unless-stopped
    networks:
      - networks-manager_default
    environment:
      SCHEDULE: '@midnight'
      BACKUP_KEEP_DAYS: 7
      PASSPHRASE: passphrase
      S3_REGION: region
      S3_ACCESS_KEY_ID: passphrase_key_id
      S3_SECRET_ACCESS_KEY: passphrase_secret_key
      S3_BUCKET: bucket_name
      S3_ENDPOINT: https://storage.yourdominio.dev
      S3_PREFIX: bkpostgres
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passphrase
networks:
  networks-manager_default:
    external: true
